Домашняя работа 1
alecsmirnov/FocusStartHomeworks pull request #1
Opened 2020-10-16 15:03 UTC by alecsmirnov

Приложение для просмотра и редактирования списка транспортных средств и их фильтрации по типу кузова.
Написано с применением паттерна MVVM. Реализован кастомный класс, предоставляющий простенький функционал выпадающего списка.

2020-10-16 17:53 UTC, korshunigor commented
Работа принята на проверку)

2020-10-17 13:36 UTC, alecsmirnov commented
Я сделал много коммитов после отправки работы. На всякий случай напишу: теперь я всё исправил

2020-10-19 14:18 UTC, alecsmirnov commented
Так можно до бесконечности улучшать

2020-10-21 12:54 UTC, noreasonwhyiamhere requested changes

2020-10-21 12:54 UTC, noreasonwhyiamhere commented on homework-1/homework-1/Model/Body.swift
> +}
а тебе понадобится как-то что енум интовый? 
просто ты потом специально ему делаешь проперти description где мапишь в строковые значения
можно было бы сделать enum Body: String и тогда в нем rawValue строка была бы (если никак не преопределать то для **case sedan** rawValue был бы  **sedan**)

2020-10-21 12:54 UTC, noreasonwhyiamhere commented on homework-1/homework-1/Model/Body.swift
> +extension Body: CaseIterable {}
можно сразу когда класс объявляешь сделать 
**enum Body: Int, CaseIterable {
}**

2020-10-21 12:54 UTC, noreasonwhyiamhere commented on homework-1/homework-1/Model/Car.swift
> +extension Car: Equatable {}
тоже можно сразу 
**struct Car: Equatable {
}**
или у тебя есть какой-то скрытый смысл так делать?)

2020-10-21 12:54 UTC, noreasonwhyiamhere commented on homework-1/homework-1/Model/CarService.swift
> +    private var tempData: [Car] = []
минор: можно еще так private var filteredData = [Car]()

2020-10-21 12:54 UTC, noreasonwhyiamhere commented on homework-1/homework-1/Model/CarService.swift
> +            fatalError("index is out of range")
круто что есть такая проверка)) но может все-таки не фаталить приложение
можно ассерт кинуть https://developer.apple.com/documentation/swift/1541112-assert
тоже самое тут ниже где проверки

2020-10-21 12:54 UTC, noreasonwhyiamhere commented on homework-1/homework-1/SceneDelegate.swift
> +        let carsViewController = navigationController.viewControllers.first as! CarsViewController
а если вдруг window.rootViewController и navigationController.viewControllers.first не скастуются к типам к которым ты пытаешься их кастануть?

2020-10-21 12:54 UTC, noreasonwhyiamhere commented on homework-1/homework-1/View/CarDetailViewController.swift
> +                    fieldData = body.description
может это тоже тогда в отдельный метод вынести?

2020-10-21 12:54 UTC, noreasonwhyiamhere commented on homework-1/homework-1/View/CarsViewController.swift
> +            }
а зачем это?)

2020-10-21 12:54 UTC, noreasonwhyiamhere commented on homework-1/homework-1/View/DropDownView.swift
> +        }
вот так можно не делать)
можно сделать так **delegate?.dropDownViewDelegate(self, itemPressedAt: row)**
и если delegate вдруг будет nil то тогда просто ничего не выполнится
ну и в целом по проекту, где также делаешь

2020-10-21 12:56 UTC, alecsmirnov commented on homework-1/homework-1/Model/Body.swift
> +}
Итовым он сделан для того, чтобы я мог получать его кейс из выпадающего списка

2020-10-21 12:57 UTC, alecsmirnov commented on homework-1/homework-1/Model/Car.swift
> +extension Car: Equatable {}
Я читал в книгах, что это хороший стиль)

2020-10-21 12:58 UTC, alecsmirnov commented on homework-1/homework-1/Model/CarService.swift
> +    private var tempData: [Car] = []
Тут не понял

2020-10-21 13:04 UTC, alecsmirnov commented on homework-1/homework-1/Model/CarService.swift
> +            fatalError("index is out of range")
Ассерты используются при дебаге, а на релизе убираются, как я знаю. 
Поэтому я сделал фатал ерроры. В приложении точно не будет ситуации, когда мы обратимся к записи которой нет (всё защищено), но на всякий случай, для гипотетического пользователя класса CarService я хочу дать понять, что доступ к несуществующей записи критичен)

2020-10-21 13:06 UTC, alecsmirnov commented on homework-1/homework-1/SceneDelegate.swift
> +        let carsViewController = navigationController.viewControllers.first as! CarsViewController
Будет краш, согласен. Тут форс анврапы забыл убрать

2020-10-21 13:09 UTC, alecsmirnov commented on homework-1/homework-1/View/CarDetailViewController.swift
> +                    fieldData = body.description
Тогда придётся выносить весь свитч и инициализацию выпадающего списка, т.к. его поле получаем из переданных данных автомобиля (типа кузова)

2020-10-21 13:14 UTC, alecsmirnov commented on homework-1/homework-1/View/CarsViewController.swift
> +            }
Чтобы обновлять тэйблВью, когда вью от CarsViewController находится на вершине иерархии вью. В противном случае, при вызове методов делегата из другого контроллера может случиться так, что вызываем методы вьюконтроллера, чьё вью находится ниже текущего и не обновляется корректно.

2020-10-21 13:15 UTC, alecsmirnov commented on homework-1/homework-1/View/DropDownView.swift
> +        }
Исправлю)
Старался избегать опционал чейнинга даже в вызове методов)

2020-10-21 13:27 UTC, alecsmirnov commented on homework-1/homework-1/Model/Body.swift
> +}
Изначально он был строковым, где по строке я получал номер, создав для этого статический метод.
Это было не слишком красиво и умно, т.к. у интового перечисления есть fallible инициалайзер по роуВалью, что заменил мне статическую функцию получения кейса по номеру и вычисления номера по строке.
Всё это исключительно для выпадающего списка. Чтобы я мог соотносить как по номеру, так и по тексту выбранного пункта.

2020-10-21 13:42 UTC, alecsmirnov commented
Исправил всё вышеописанное :)

2020-10-21 18:45 UTC, noreasonwhyiamhere commented on homework-1/homework-1/Model/Car.swift
> +extension Car: Equatable {}
ну это как мне кажется дело вкуса, я по-другому привыкла) 
в целом да, обычно когда реализуешь какой-то протокол, то лучше через  extension, но лично я так делаю только если какие-то методы/проперти надо реализовать или очень много протоколов нужно поддержать в классе

2020-10-21 18:46 UTC, noreasonwhyiamhere commented on homework-1/homework-1/Model/CarService.swift
> +            fatalError("index is out of range")
ага ассерты только на дебаге

2020-10-21 18:48 UTC, noreasonwhyiamhere commented on homework-1/homework-1/View/DropDownView.swift
> +        }
ну в целом тут нет смысла его избегать, так как если он nil, то ничего не будет)

2020-10-21 18:59 UTC, noreasonwhyiamhere requested changes

2020-10-21 18:59 UTC, noreasonwhyiamhere commented on homework-1/homework-1/View/CarsViewController.swift
> +            }
хммм а зачем нам вызывать это, когда мы находимся на каком-то другом VC?

2020-10-21 18:59 UTC, noreasonwhyiamhere commented on homework-1/homework-1/View/DropDownView.swift
> +        }
тут тоже можно не разворачивать а через ? обратиться

2020-10-21 18:59 UTC, noreasonwhyiamhere commented on homework-1/homework-1/View/DropDownView.swift
> +        isClosed = !isClosed
наличие таких флажков всегда не оч, так как надо отслеживать их стейт, он точно нужен? почему просто не сделать тип такого 
**rowButtons.forEach { rowButton in
            UIView.animate(withDuration: 0.3) {
                rowButton.isHidden.toggle()
                rowButton.alpha = rowButton.alpha == 0 ? 1 : 0
            }
        }**

2020-10-21 18:59 UTC, noreasonwhyiamhere commented on homework-1/homework-1/ViewModel/CarDetailViewModel.swift
> +            yearOfIssue = "-"
подобное разрешение ситуации с опциональным yearOfIssue есть еще в CarCellViewModel
кмк надо как-то сделать чтобы в 1 месте было, иначе рассинхрон какой-то может быть

2020-10-21 18:59 UTC, noreasonwhyiamhere commented on homework-1/homework-1/ViewModel/CarsViewModel.swift
> +        }
тут тоже можно убрать)

2020-10-22 04:33 UTC, alecsmirnov commented on homework-1/homework-1/View/CarsViewController.swift
> +            }
У меня цепочка коммуникаций: **CarDetailViewModel** -> **CarsViewModel**.
**CarsViewModel** -- делегат **CarDetailViewModel**. Используется делегирование по той причине, что **CarDetail** неважно кто реализует редактирование записи. Ему важно лишь то, что какой-то делегат это делает.
Из-за этого, в момент, когда мы вызываем методы делегата, находясь в **CarDetailViewController**, происходит вызов в **CarsViewController** (Он является дисплей делегатом своей модели, чтобы отслеживать обновление данных модели).
Чтобы этот вызов _не происходил_ тогда, когда мы находимся на экране **CarDetailViewController** -- инициализируем задачу на обновление и исполняем её перед появлением вью, когда оно перемещается на самый верх иерархии

2020-10-22 04:34 UTC, alecsmirnov commented on homework-1/homework-1/View/DropDownView.swift
> +        }
Тут нельзя, т.к. в случае неудачи будет присвоение **nil**-у

2020-10-22 04:46 UTC, alecsmirnov commented on homework-1/homework-1/View/DropDownView.swift
> +        isClosed = !isClosed
Я оставил его с заделом на то, что где-то может понадобиться отслеживать его состояние (открыт закрыт), но в данном случае, т.к. проект "финальный" -- флаг состояния лишний.
Исправил)

2020-10-22 04:47 UTC, alecsmirnov commented on homework-1/homework-1/ViewModel/CarsViewModel.swift
> +        }
Уже было исправлено, когда я написал)

2020-10-22 05:01 UTC, alecsmirnov commented on homework-1/homework-1/ViewModel/CarDetailViewModel.swift
> +            yearOfIssue = "-"
Верно. Убрал **yearOfIssue = "-"** из CarDetailViewModel, там она не нужна

2020-10-22 05:09 UTC, alecsmirnov commented
Исправил новые замечания, кроме вопроса с DispatchWorkItem. На него я ответил с беседе выше.
На всякий случай, прикрепляю ссылку на беседу и свой ответ ниже:
https://github.com/alecsmirnov/FocusStartHomeworks/pull/1#discussion_r509873654

2020-10-22 13:02 UTC, alecsmirnov commented on homework-1/homework-1/View/CarsViewController.swift
> +            }
Уберу GDC)

2020-10-22 13:32 UTC, alecsmirnov commented
Исправил все новые замечания)

2020-10-22 18:20 UTC, noreasonwhyiamhere commented on homework-1/homework-1/View/DropDownView.swift
> +        }
точно нельзя?)

2020-10-22 18:25 UTC, alecsmirnov commented on homework-1/homework-1/View/DropDownView.swift
> +        }
Вы правы, можно)

2020-10-22 18:26 UTC, noreasonwhyiamhere commented on homework-1/homework-1/View/DropDownView.swift
> +        }
можно на ты)

2020-10-22 18:27 UTC, alecsmirnov commented on homework-1/homework-1/View/DropDownView.swift
> +        }
Не знаю почему, опшинал чейнинг вызывает у меня неприятные чувства)

2020-10-22 18:29 UTC, noreasonwhyiamhere commented on homework-1/homework-1/Model/CarService.swift
> +    private var tempData: [Car] = []
угу чет съелись да) но тут так вкусовщина

2020-10-22 18:31 UTC, noreasonwhyiamhere commented on homework-1/homework-1/View/DropDownView.swift
> +        }
ахахах ну крч присваивать опшиналу и дегать методы у того, что может быть опшинал ок)
но если тебе надо достать данные из чего-то что может быть опшинал и присвоить или передать куда-то где должно точно быть значение, тогда да, надо разворачивать

2020-10-22 18:32 UTC, noreasonwhyiamhere commented on homework-1/homework-1/View/DropDownView.swift
> +        }
вот если бы ты сделал **fieldButton.titleLabel!.font = UIFont.systemFont(ofSize: fontSize)** тогда да это плохо

2020-10-22 18:35 UTC, alecsmirnov commented on homework-1/homework-1/View/DropDownView.swift
> +        }
Понял) Исправил)

2020-10-22 18:38 UTC, alecsmirnov commented on homework-1/homework-1/View/DropDownView.swift
> +        }
Тогда, все проверки на вьюМодель, на манер этой:
        **if let carsViewModel = carsViewModel {
            carsViewModel.selectedRow = indexPath.row
        }**
Мне стоит поменять на:
**carsViewModel?.selectedRow = indexPath.row**
Верно?

2020-10-22 18:41 UTC, noreasonwhyiamhere commented on homework-1/homework-1/View/DropDownView.swift
> +        }
угу, ну как мне кажется так выглядит читабельнее
это не ошибка, просто излишний код (а лучший код - это тот, который не был написан 🤡)

2020-10-22 18:46 UTC, alecsmirnov commented on homework-1/homework-1/View/DropDownView.swift
> +        }
Понял! Исправил, спасибо!)

2020-10-23 02:36 UTC, alecsmirnov commented
На данный момент исправлены все замечания)

2020-10-24 08:22 UTC, alecsmirnov commented
Исправлены все замечания)

2020-10-25 15:17 UTC, noreasonwhyiamhere approved these changes
такс ну вроде все, хотя может и не все конечно)

2020-10-25 15:20 UTC, alecsmirnov commented
@noreasonwhyiamhere про "может и не всё" не очень оптимистично звучит)

2020-10-25 15:23 UTC, noreasonwhyiamhere commented
в общем можно мержить)

2020-10-25 15:43 UTC, merged